### ISSUE TITLE
Why create potentially large bytes objects initialized with null bytes ?

### ISSUE THREAD

**Issue by joergschulz** [authlib/otpauth#10]
https://github.com/authlib/otpauth/blob/22368eb2778fad0e0fc71340174c509de1cad6c2/src/otpauth/rfc6238.py#L43

hmac.compare_digest()  accepts either str or bytes and python doc says it should be used to lower the risk of timing attacks. 

But what's the purpose of creating potentially large bytes objects initialized with null bytes ?

Shouldn't be simply the strings of the codes be compared ?

**Comment by lepture** [comment]
Oh, you are right. This is certainly a wrong way. You're welcome to send a PR.

**Comment by lepture** [comment]
2.1.1 released
